name: finances-ms-DEV-CI

on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test
        
      - name: Build aplication
        run: npm run build

      - name: Docker login
        run: |
          docker login ${{ secrets.REGISTRY_SERVER }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}
        
      - name: Build docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_SERVER }}/finances-ms -t ${{ secrets.REGISTRY_SERVER }}/finances-ms:${{ github.sha }} .
          
      - name: Docker push
        run: |
          docker push ${{ secrets.REGISTRY_SERVER }}/finances-ms:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_SERVER }}/finances-ms:latest

      - name: Docker logout
        run: |
          docker logout ${{ secrets.REGISTRY_SERVER }}
